name: Replace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  replace-imports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Replace local imports with package name
        run: |
          find examples/math -type f -name "*.js" -print0 | xargs -0 sed -i 's|../../dist/index|@thainanluiz/tssuper|g'
